VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IComparer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit
'@Folder("Comparers")
'@Interface
'@PredeclaredId
'@Exposed
Public Function ExecCmp(ByRef ipHostItem As Variant) As Boolean
End Function

Public Function Item() As Variant
End Function

